### ISSUE TITLE
Using AddLink() on Attachments causes NullReferenceException when saving the email.

### ISSUE THREAD

**Issue by lorant-csonka** [Sicos1977/MsgKit#62]
### Description
I get NullRef exception when trying to use `AddLink()` function on the `Attachments`, and then try to save the e-mail.
It's like the wrong `Attachment ctor` get's called.
Also it would be really handy to have access to the `Attachment` ctor.

### Steps to Reproduce
```
using (var email = new Email(
        new Sender("peterpan@neverland.com", "Peter Pan"),
        new Representing("tinkerbell@neverland.com", "Tinkerbell"),
        "Hello Neverland subject"))
{
    email.Recipients.AddTo("captainhook@neverland.com", "Captain Hook");
    email.Recipients.AddCc("crocodile@neverland.com", "The evil ticking crocodile");
    email.Subject = "This is the subject";
    email.BodyText = "Hello Neverland text";
    email.BodyHtml = "<html><head></head><body><b>Hello Neverland html</b></body></html>";
    email.Importance = MessageImportance.IMPORTANCE_HIGH;
    email.IconIndex = MessageIconIndex.ReadMail;
    email.Attachments.AddLink(new FileInfo(@"d:\crocodile.jpg"));
    email.Save(@"c:\email.msg");

    // Show the E-mail
    System.Diagnostics.Process.Start(@"c:\email.msg");
}
```

### Actual Behavior
It throws NRE.
```
{"Object reference not set to an instance of an object."}
  at MsgKit.Attachment.WriteProperties(CFStorage storage, Int32 index)
  at MsgKit.Attachments.WriteToStorage(CFStorage rootStorage)
  at MsgKit.Email.WriteToStorage()
  at MsgKit.Email.Save(String fileName)
```

**Comment by Sicos1977** [comment]
This commit 732f107d8006cbe13004fbb46e2e16024d29b79d fixes this issue
